Release changes

diff --git a/.github/workflows/npm.build.release.yml b/.github/workflows/npm.build.release.yml
--- a/.github/workflows/npm.build.release.yml
+++ b/.github/workflows/npm.build.release.yml
@@ -3,7 +3,7 @@ on:
   workflow_dispatch:
     inputs: 
       tag_name:
-        description: 'Tag name for the release - v1.4.7'
+        description: 'Tag name for the release - 1.4.7'
         required: true
       release_name:
         description: 'Release name - Verze 1.4.7'
@@ -18,6 +18,16 @@ jobs:
         node-version: [14.x]
     
     steps:
+        
+    - name: Check if tag_name starts with 'v'
+      id: check_tag_name
+      run: |
+        TAG_NAME="${{ inputs.tag_name }}"
+        if [[ $TAG_NAME != v* ]]; then
+          echo "Error: tag_name must start with 'v'."
+          exit 1
+        fi
+    
     # Build 
     - uses: actions/checkout@v3
     - name: Use Node.js ${{ matrix.node-version }}
@@ -44,16 +54,12 @@ jobs:
       with:
         name: kramerius-admin
         path: dist-zip/kramerius-admin.zip
-    
-    # Create release and upload artifact
-    #- uses: "marvinpinto/action-automatic-releases@latest"
-    #  with:
-    #    repo_token: "${{ secrets.GITHUB_TOKEN }}"
-    #    prerelease: false
-    #    files: |
-    #      LICENSE.txt
-    #      dist-zip/*.zip
 
+
+    - name: List files in runner.temp directory
+      run: |
+        ls -la ${{ runner.temp }}
+    
     # Prepare release      
     - name: Create Release
       id: create_release
@@ -61,12 +67,27 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
-        tag_name: ${{ inputs.tag_name }}
+        tag_name: v${{ inputs.tag_name }}
         release_name: ${{ inputs.release_name }}
         body: |
           Description of the release
         draft: true
         prerelease: false
+        
+
+    - name: Extract version from tag_name
+      id: extract_version
+      run: |
+        TAG_NAME="${{ inputs.tag_name }}"
+        if [[ $TAG_NAME == v* ]]; then
+          VERSION_NO_V=${TAG_NAME:1}
+        else
+          VERSION_NO_V=$TAG_NAME
+        fi
+        VERSION_WITH_V="v${VERSION_NO_V}"
+        echo "::set-output name=version_without_v::$VERSION_NO_V"
+        echo "::set-output name=version_with_v::$VERSION_WITH_V"
+        
     
     # Upload release asset 
     - name: Upload Release Asset
@@ -95,5 +116,5 @@ jobs:
       with:
         context: .
         push: true
-        tags: ceskaexpedice/kramerius-admin-client:${{inputs.release_name}}
+        tags: ceskaexpedice/kramerius-admin-client:${{steps.extract_version.outputs.version_without_v}}
         build-args: ADMIN_ADDR=${{ runner.temp }}/dist/kramerius-admin
